context = '''
In a dangerous dense traffic scenario with 70 vehicles on the road, during a mid-rainy noon, 40% of the vehicles are being dangerously driven in crowded traffic. These vehicles ignore traffic signs, lights, and other vehicles but do not ignore pedestrians, increasing the risk of accidents. There are 100 pedestrians navigating the challenging weather conditions which 30 percent of them are running.
'''
# Please generate the scenario according to the following information:
# Time: 10:34; Weather: Clear; VehicleStates: Crashed; Vehicle: 3; PedestrianCount: 3; PercentagePedestrianRunning: 0%; VehicleDoors: [Opened]; Location: Intersection; Event: Collision; Severity: High.


# In a dangerous sparse scenario with only 5 vehicles, during a wet and cloudy noon, 3 of the vehicles have wrong lights. These vehicles exhibit negligence towards traffic signs and lights, one of them ignores everything. There are 15 pedestrians on the wet road, with 2 pedestrians running and 11 pedestrians crossing, 2 jumping with an interval of 5 seconds.

# In a semi-dangerous vehicle scenario, during a wet and cloudy noon, 30% of the vehicles have wrong lights, and one of the vehicles having its all doors opened. These vehicles exhibit negligence towards traffic signs and lights. There are 10 pedestrians on the wet road, with 3 pedestrians running and 7 pedestrians crossing.

# In a safe dense traffic scenario, during a mid-rainy sunset, there are 20 vehicles and 15 pedestrians sharing the road. Some pedestrians are running, while others are crossing. Some vehicles update their lights, enhancing visibility in the challenging weather conditions.

# In an intern vehicle scenario, during a soft rainy noon, there are 2 intern vehicles on the road. These vehicles are semi-dangerous with their left doors opened, and maintaining a far distance from other objects. There are 3 pedestrians navigating the wet conditions.

# It's raining cats and dogs! In a semi-dangerous vehicle scenario, during a wet sunset, 20% of the vehicles have wrong lights. The semi-dangerous vehicles exhibit negligence towards traffic signs and lights. There are 5 pedestrians on the wet road, with one pedestrian jumping once per interval.

# In a safe sparse traffic scenario, during a clear sunset, there are 3 vehicles and 2 pedestrians on the road. One of the vehicles is being driven dangerously, exhibiting negligence towards traffic signs. And  its all doors are opened. The pedestrians and vehicles maintain a safe distance from each other.

# In a dangerous dense traffic scenario, during a cloudy noon, 50% of the vehicles are being dangerously driven in crowded traffic, posing a significant risk to other road users, ignoring anything. There are 15 pedestrians navigating the congested area.

# In a safe dense traffic scenario, during a clear noon, there are 30 vehicles and 20 pedestrians sharing the road. Some pedestrians are running, while others are crossing. Safe vehicles operate in autopilot mode and strictly obey traffic rules.

# On a sunny morning, there are 5 pedestrians walking on the street, accompanied by 7 vehicles being driven. One vehicle has opened all all of its doors and ignores the pedestrians on the road, but it does not ignore other traffic objects like vehicles, lights, or signs.

# On a rainy day with hard rain, there is a traffic jam. There are 20 pedestrians walking, 10 pedestrians running, and 5 pedestrians crossing. Inside the traffic jam, there is a dangerous vehicle with broken compartments, including no vehicle lights and opened doors, ignoring everything and causing collisions with pedestrians and other vehicles.


# On a cloudy afternoon there are 5 vehicles on the road, among them there are 3 dangerous vehicles, one of them ignoring all the traffic lights, one of them ignoring all the pedestrians, one of them ignoring all the other vehicles. There are also 30 pedestrian in this scenario, 3 of them are busily running.


batch_context = [
'''On a rainy day with hard rain, there is a traffic jam. There are 20 pedestrians walking, 10 pedestrians running, and 5 pedestrians crossing. Inside the traffic jam, there is a dangerous vehicle with broken compartments, including no vehicle lights and opened doors, ignoring everything and causing collisions with pedestrians and other vehicles.''',
'''On a sunny morning, there are 5 pedestrians walking on the street, accompanied by 7 vehicles being driven. One vehicle has opened all its doors and ignores the pedestrians on the road, but it does not ignore other traffic objects like vehicles, lights, or signs.''',
'''In a safe dense traffic scenario, during a clear noon, there are 30 vehicles and 20 pedestrians sharing the road. Some pedestrians are running, while others are crossing. Safe vehicles operate in autopilot mode and strictly obey traffic rules.''',
'''In a dangerous dense traffic scenario, during a cloudy noon, 50% of the vehicles are being dangerously driven in crowded traffic, posing a significant risk to other road users. There are 15 pedestrians navigating the congested area.''',
'''In a safe sparse traffic scenario, during a clear sunset, there are 3 vehicles and 2 pedestrians on the road. One of the vehicles is being driven dangerously, exhibiting negligence towards traffic signs. The pedestrians and vehicles maintain a safe distance from each other.''',
'''In a semi-dangerous vehicle scenario, during a wet sunset, 20% of the vehicles have wrong lights. The semi-dangerous vehicles exhibit negligence towards traffic signs and lights. There are 5 pedestrians on the wet road, with one pedestrian jumping once per interval.''',
'''In an intern vehicle scenario, during a soft rainy noon, there are 2 intern vehicles on the road. These vehicles are semi-dangerous, maintaining a far distance from other objects. At some point, one of the intern vehicles unintentionally opens its door. There are 3 pedestrians navigating the wet conditions.''',
'''In a safe dense traffic scenario, during a mid-rainy sunset, there are 20 vehicles and 15 pedestrians sharing the road. Some pedestrians are running, while others are crossing. Some vehicles update their lights, enhancing visibility in the challenging weather conditions.''',
'''In a semi-dangerous vehicle scenario, during a wet and cloudy noon, 30% of the vehicles have wrong lights. These vehicles exhibit negligence towards traffic signs and lights. There are 10 pedestrians on the wet road, with 3 pedestrians running and 7 pedestrians crossing.''',
'''In a safe dense traffic scenario, during a clear noon, there are 40 vehicles and 25 pedestrians sharing the road. Some pedestrians are running, while others are crossing. Safe vehicles operate in autopilot mode and strictly obey traffic rules.''',
'''In a dangerous dense traffic scenario, during a hard rainy sunset, 70% of the vehicles are being dangerously driven in crowded traffic. These vehicles ignore traffic signs, lights, and other vehicles, increasing the risk of accidents. There are 20 pedestrians navigating the challenging weather conditions.''',
'''In a safe sparse traffic scenario, during a wet and cloudy noon, there are 2 vehicles and 3 pedestrians on the road. One of the vehicles is being driven dangerously, exhibiting negligence towards traffic signs and lights. The pedestrians and vehicles maintain a safe distance from each other.''',
'''In a safe dense traffic scenario, during a clear sunset, there are 25 vehicles and 20 pedestrians sharing the road. Some pedestrians are running, while others are crossing. Safe vehicles operate in autopilot mode and strictly obey traffic rules.''',
'''In a semi-dangerous vehicle scenario, during a soft rainy noon, 10% of the vehicles have wrong lights. These vehicles exhibit negligence towards traffic signs and lights. There are 10 pedestrians on the wet road, with 2 pedestrians running and 8 pedestrians crossing.''',
'''In a safe dense traffic scenario, during a clear noon, there are 30 vehicles and 25 pedestrians sharing the road. Some pedestrians are running, while others are crossing. Safe vehicles operate in autopilot mode and strictly obey traffic rules.''',
'''In a safe sparse traffic scenario, during a wet and cloudy sunset, there are 3 vehicles and 2 pedestrians on the road. One of the vehicles is being driven dangerously, exhibiting negligence towards traffic signs and lights. The pedestrians and vehicles maintain a safe distance from each other.''',
'''In a dangerous dense traffic scenario, during a mid-rainy noon, 40% of the vehicles are being dangerously driven in crowded traffic. These vehicles ignore traffic signs, lights, and other vehicles, increasing the risk of accidents. There are 15 pedestrians navigating the challenging weather conditions.''',
'''In a safe dense traffic scenario, during a clear sunset, there are 20 vehicles and 15 pedestrians sharing the road. Some pedestrians are running, while others are crossing. A semi-dangerous vehicle with wrong lights occasionally changes lanes negligently, posing a potential risk to other road users.''',
'''In a dangerous vehicle scenario, during a wet and cloudy noon, 20% of the vehicles have wrong lights. These vehicles exhibit negligence towards traffic signs and lights. There are 5 pedestrians on the wet road, with 2 pedestrians running and 3 pedestrians crossing.''',
'''In a safe sparse traffic scenario, during a soft rainy sunset, there are 2 vehicles and 3 pedestrians on the road. Intern vehicles, which are semi-dangerous, maintain a safe distance from other objects but occasionally unintentionally open their doors, requiring caution from other road users.''',
'''In a safe dense traffic scenario, during a clear noon, there are 30 vehicles and 20 pedestrians sharing the road. Some pedestrians are running, while others are crossing. Safe vehicles operate in autopilot mode and strictly obey traffic rules.''',
'''In a dangerous dense traffic scenario, during a cloudy noon, 50% of the vehicles are being dangerously driven in crowded traffic, posing a significant risk to other road users. There are 15 pedestrians navigating the congested area.''',
'''In a safe sparse traffic scenario, during a clear sunset, there are 3 vehicles and 2 pedestrians on the road. One of the vehicles is being driven dangerously, exhibiting negligence towards traffic signs. The pedestrians and vehicles maintain a safe distance from each other. Please note that these scenario descriptions tightly contain the specified scenario attributes, including specific values for pedestrians, vehicles, their behaviors, dangerous and semi-dangerous vehicles, intern vehicles, safe vehicles, dense and sparse traffic, varying vehicle light states, and different weather conditions.''',
'''On a rainy day, there is a traffic jam. There are 20 people walking and 2 people running. Inside traffic jam, there is a dangerous vehicle ignoring everything and making collisions with the pedestrians as well as other vehicles.''',
'''On a sunny morning, there are 5 people walking on the street, with 7 vehicles also being driven on the street. There is a vehicle which has opened all of its door and ignoring the pedestrians on the road. But it does not ignore other traffic objects like vehicles or lights or signs.''',
'''On a snowy day with heavy snowfall, there is a traffic jam. There are 15 pedestrians walking, 5 pedestrians running, and 3 pedestrians crossing. Inside the traffic jam, there is a dangerous vehicle with malfunctioning brakes, ignoring traffic signals and causing near-miss incidents with pedestrians and other vehicles.''',
'''During a foggy morning, there are 8 pedestrians walking on the street, accompanied by 10 vehicles being driven. One vehicle has its windows covered in mist, obstructing the driver's visibility and posing a potential risk to pedestrians and other vehicles.''',
'''In a safe dense traffic scenario, during a sunny afternoon, there are 40 vehicles and 30 pedestrians sharing the road. Some pedestrians are jogging, while others are waiting at crosswalks. Safe vehicles operate in autonomous mode, following traffic rules and maintaining a safe distance from other objects.''',
'''In a dangerous dense traffic scenario, during a rainy noon, 60% of the vehicles are being recklessly driven in congested traffic, creating a hazardous environment for other road users. There are 25 pedestrians navigating the chaotic conditions, with some seeking shelter from the rain.''',
'''In a safe sparse traffic scenario, during a clear evening, there are 4 vehicles and 3 pedestrians on the road. One of the vehicles is being driven aggressively, constantly changing lanes without signaling. The pedestrians and other vehicles maintain a safe distance from each other.''',
'''In a semi-dangerous vehicle scenario, during a drizzly afternoon, 15% of the vehicles have malfunctioning turn signals. These vehicles exhibit erratic behavior, ignoring traffic signs and making sudden lane changes. There are 6 pedestrians on the wet road, with one pedestrian carrying an open umbrella.''',
'''In an intern vehicle scenario, during a light rain in the morning, there are 2 intern vehicles on the road. These vehicles are still learning and occasionally make abrupt stops or slow down unexpectedly. There are 4 pedestrians navigating the wet conditions, taking extra caution around the intern vehicles.''',
'''In a safe dense traffic scenario, during a hazy sunset, there are 30 vehicles and 20 pedestrians sharing the road. Some pedestrians are walking briskly, while others are using designated crosswalks. Some vehicles have their headlights on, improving visibility in the challenging weather conditions.''',
'''In a semi-dangerous vehicle scenario, during a foggy and rainy noon, 25% of the vehicles have malfunctioning brake lights. These vehicles exhibit reckless driving behavior, frequently tailgating and ignoring traffic signals. There are 12 pedestrians on the wet road, with 4 pedestrians running and 8 pedestrians crossing.''',
'''In a safe dense traffic scenario, during a clear morning, there are 35 vehicles and 25 pedestrians sharing the road. Some pedestrians are walking leisurely, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, obeying traffic laws and prioritizing pedestrian safety.''',
'''In a dangerous dense traffic scenario, during a stormy evening, 80% of the vehicles are being driven aggressively in heavy traffic. These vehicles disregard lane markings and speed limits, posing a severe threat to pedestrians and other vehicles. There are 30 pedestrians navigating the challenging weather conditions.''',
'''In a safe sparse traffic scenario, during a foggy and drizzly afternoon, there are 2 vehicles and 4 pedestrians on the road. One of the vehicles is being driven recklessly, frequently overtaking other vehicles in low visibility conditions. The pedestrians and vehicles maintain a safe distance from each other.''',
'''In a safe dense traffic scenario, during a clear morning, there are 25 vehicles and 20 pedestrians sharing the road. Some pedestrians are walking at a moderate pace, while others are using pedestrian crossings. Safe vehicles operate in autonomous mode, ensuring smooth traffic flow and pedestrian safety.''',
'''In a semi-dangerous vehicle scenario, during a misty noon, 12% of the vehicles have malfunctioning headlights. These vehicles exhibit negligent driving behavior, failing to illuminate the road properly. There are 8 pedestrians on the misty road, with 2 pedestrians running and 6 pedestrians crossing.''',
'''In a safe dense traffic scenario, during a clear afternoon, there are 30 vehicles and 25 pedestrians sharing the road. Some pedestrians are walking briskly, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, prioritizing pedestrian safety and maintaining a constant speed.''',
'''In a safe sparse traffic scenario, during a foggy and drizzly evening, there are 3 vehicles and 2 pedestrians on the road. One of the vehicles is being driven recklessly, frequently swerving between lanes without signaling. The pedestrians and vehicles maintain a safe distance from each other.''',
'''In a dangerous dense traffic scenario, during a misty morning, 50% of the vehicles are being driven aggressively in congested traffic. These vehicles disregard traffic rules, causing frequent near-miss incidents with pedestrians and other vehicles. There are 15 pedestrians navigating the challenging weather conditions.''',
'''In a safe dense traffic scenario, during a clear evening, there are 20 vehicles and 15 pedestrians sharing the road. Some pedestrians are walking at a steady pace, while others are using pedestrian crossings. A semi-dangerous vehicle occasionally exceeds the speed limit, posing a potential risk to other road users.''',
'''In a dangerous vehicle scenario, during a foggy and drizzly afternoon, 18% of the vehicles have malfunctioning headlights. These vehicles exhibit negligent driving behavior, disregarding traffic signs and failing to use turn signals. There are 5 pedestrians on the wet road, with 2 pedestrians running and 3 pedestrians crossing.''',
'''In a safe sparse traffic scenario, during a misty evening, there are 2 vehicles and 3 pedestrians on the road. Intern vehicles, which are still learning, occasionally make sudden stops or slow down unexpectedly. The pedestrians and other vehicles exercise caution when encountering the intern vehicles.''',
'''On a windy day with gusty winds, there is a traffic jam. There are 25 pedestrians walking, 8 pedestrians running, and 4 pedestrians crossing. Inside the traffic jam, there is a dangerous vehicle with a faulty horn, making it difficult for other road users to be alerted of its presence.''',
'''During a sunny afternoon, there are 10 pedestrians walking on the street, accompanied by 12 vehicles being driven. One vehicle has a cracked windshield, obstructing the driver's view and potentially compromising safety on the road.''',
'''In a safe dense traffic scenario, during a cloudy morning, there are 35 vehicles and 25 pedestrians sharing the road. Some pedestrians are walking briskly, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, ensuring smooth traffic flow and pedestrian safety.''',
'''In a dangerous dense traffic scenario, during a rainy evening, 55% of the vehicles are being recklessly driven in congested traffic, posing a significant risk to other road users. There are 20 pedestrians navigating the chaotic conditions, seeking shelter from the rain.''',
'''In a safe sparse traffic scenario, during a clear night, there are 4 vehicles and 3 pedestrians on the road. One of the vehicles is being driven aggressively, frequently changing lanes without signaling. The pedestrians and other vehicles maintain a safe distance from each other.''',
'''In a semi-dangerous vehicle scenario, during a drizzly morning, 20% of the vehicles have malfunctioning windshield wipers. These vehicles exhibit negligent driving behavior, compromising visibility in wet conditions. There are 7 pedestrians on the road, with one pedestrian carrying a large umbrella.''',
'''In an intern vehicle scenario, during a light rain in the evening, there are 2 intern vehicles on the road. These vehicles are still learning and occasionally hesitate at intersections, causing minor delays. There are 4 pedestrians navigating the wet conditions, exercising caution around the intern vehicles.''',
'''In a safe dense traffic scenario, during a hazy morning, there are 30 vehicles and 20 pedestrians sharing the road. Some pedestrians are jogging, while others are waiting at designated crosswalks. Some vehicles have their fog lights on, improving visibility in the challenging weather conditions.''',
'''In a semi-dangerous vehicle scenario, during a foggy and rainy afternoon, 30% of the vehicles have malfunctioning turn signals. These vehicles exhibit erratic behavior, making sudden lane changes without signaling. There are 10 pedestrians on the wet road, with 3 pedestrians running and 7 pedestrians crossing.''',
'''In a safe dense traffic scenario, during a clear morning, there are 35 vehicles and 25 pedestrians sharing the road. Some pedestrians are walking leisurely, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, prioritizing pedestrian safety and maintaining a steady pace.''',
'''In a dangerous dense traffic scenario, during a stormy evening, 75% of the vehicles are being driven aggressively in heavy traffic. These vehicles disregard lane markings and speed limits, posing a severe threat to pedestrians and other vehicles. There are 25 pedestrians navigating the challenging weather conditions.''',
'''In a safe sparse traffic scenario, during a foggy and drizzly morning, there are 2 vehicles and 4 pedestrians on the road. One of the vehicles is being driven recklessly, frequently overtaking other vehicles in low visibility conditions. The pedestrians and vehicles maintain a safe distance from each other.''',
'''In a safe dense traffic scenario, during a clear morning, there are 25 vehicles and 20 pedestrians sharing the road. Some pedestrians are walking briskly, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, ensuring smooth traffic flow and pedestrian safety.''',
'''In a semi-dangerous vehicle scenario, during a misty afternoon, 10% of the vehicles have malfunctioning headlights. These vehicles exhibit negligent driving behavior, failing to illuminate the road properly. There are 8 pedestrians on the misty road, with 2 pedestrians running and 6 pedestrians crossing.''',
'''In a safe dense traffic scenario, during a clear morning, there are 30 vehicles and 25 pedestrians sharing the road. Some pedestrians are walking leisurely, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, prioritizing pedestrian safety and maintaining a constant speed.''',
'''In a safe sparse traffic scenario, during a foggy and drizzly evening, there are 3 vehicles and 2 pedestrians on the road. One of the vehicles is being driven recklessly, frequently swerving between lanes without signaling. The pedestrians and vehicles maintain a safe distance from each other.''',
'''In a dangerous dense traffic scenario, during a misty morning, 45% of the vehicles are being driven aggressively in congested traffic. These vehicles disregard traffic rules, causing frequent near-miss incidents with pedestrians and other vehicles. There are 15 pedestrians navigating the challenging weather conditions.''',
'''In a safe dense traffic scenario, during a clear evening, there are 20 vehicles and 15 pedestrians sharing the road. Some pedestrians are walking at a moderate pace, while others are using pedestrian crossings. A semi-dangerous vehicle occasionally exceeds the speed limit, posing a potential risk to other road users.''',
'''In a dangerous vehicle scenario, during a foggy and drizzly afternoon, 15% of the vehicles have malfunctioning headlights. These vehicles exhibit negligent driving behavior, disregarding traffic signs and failing to use turn signals. There are 5 pedestrians on the wet road, with 2 pedestrians running and 3 pedestrians crossing.''',
'''In a safe sparse traffic scenario, during a misty evening, there are 2 vehicles and 3 pedestrians on the road. Intern vehicles, which are still learning, occasionally make sudden stops or slow down unexpectedly. The pedestrians and other vehicles exercise caution when encountering the intern vehicles.''',
'''On a windy day with gusty winds, there is a traffic jam. There are 25 pedestrians walking, 8 pedestrians running, and 4 pedestrians crossing. Inside the traffic jam, there is a dangerous vehicle with a faulty horn, making it difficult for other road users to be alerted of its presence.''',
'''During a sunny afternoon, there are 10 pedestrians walking on the street, accompanied by 12 vehicles being driven. One vehicle has a cracked windshield, obstructing the driver's view and potentially compromising safety on the road.''',
'''In a safe dense traffic scenario, during a cloudy morning, there are 35 vehicles and 25 pedestrians sharing the road. Some pedestrians are walking briskly, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, ensuring smooth traffic flow and pedestrian safety.''',
'''In a dangerous dense traffic scenario, during a rainy evening, 55% of the vehicles are being recklessly driven in congested traffic, posing a significant risk to other road users. There are 20 pedestrians navigating the chaotic conditions, seeking shelter from the rain.''',
'''In a safe sparse traffic scenario, during a clear night, there are 4 vehicles and 3 pedestrians on the road. One of the vehicles is being driven aggressively, frequently changing lanes without signaling. The pedestrians and other vehicles maintain a safe distance from each other.''',
'''In a semi-dangerous vehicle scenario, during a drizzly morning, 20% of the vehicles have malfunctioning windshield wipers. These vehicles exhibit negligent driving behavior, compromising visibility in wet conditions. There are 7 pedestrians on the road, with one pedestrian carrying a large umbrella.''',
'''In an intern vehicle scenario, during a light rain in the evening, there are 2 intern vehicles on the road. These vehicles are still learning and occasionally hesitate at intersections, causing minor delays. There are 4 pedestrians navigating the wet conditions, exercising caution around the intern vehicles.''',
'''In a safe dense traffic scenario, during a hazy morning, there are 30 vehicles and 20 pedestrians sharing the road. Some pedestrians are jogging, while others are waiting at designated crosswalks. Some vehicles have their fog lights on, improving visibility in the challenging weather conditions.''',
'''In a semi-dangerous vehicle scenario, during a foggy and rainy afternoon, 30% of the vehicles have malfunctioning turn signals. These vehicles exhibit erratic behavior, making sudden lane changes without signaling. There are 10 pedestrians on the wet road, with 3 pedestrians running and 7 pedestrians crossing.''',
'''In a safe dense traffic scenario, during a clear morning, there are 35 vehicles and 25 pedestrians sharing the road. Some pedestrians are walking leisurely, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, prioritizing pedestrian safety and maintaining a steady pace.''',
'''In a dangerous dense traffic scenario, during a stormy evening, 75% of the vehicles are being driven aggressively in heavy traffic. These vehicles disregard lane markings and speed limits, posing a severe threat to pedestrians and other vehicles. There are 25 pedestrians navigating the challenging weather conditions.''',
'''In a safe sparse traffic scenario, during a foggy and drizzly morning, there are 2 vehicles and 4 pedestrians on the road. One of the vehicles is being driven recklessly, frequently overtaking other vehicles in low visibility conditions. The pedestrians and vehicles maintain a safe distance from each other.''',
'''In a safe dense traffic scenario, during a clear morning, there are 25 vehicles and 20 pedestrians sharing the road. Some pedestrians are walking briskly, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, ensuring smooth traffic flow and pedestrian safety.''',
'''In a semi-dangerous vehicle scenario, during a misty afternoon, 10% of the vehicles have malfunctioning headlights. These vehicles exhibit negligent driving behavior, failing to illuminate the road properly. There are 8 pedestrians on the misty road, with 2 pedestrians running and 6 pedestrians crossing.''',
'''In a safe dense traffic scenario, during a clear morning, there are 30 vehicles and 25 pedestrians sharing the road. Some pedestrians are walking leisurely, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, prioritizing pedestrian safety and maintaining a constant speed.''',
'''In a safe sparse traffic scenario, during a foggy and drizzly evening, there are 3 vehicles and 2 pedestrians on the road. One of the vehicles is being driven recklessly, frequently swerving between lanes without signaling. The pedestrians and vehicles maintain a safe distance from each other.''',
'''In a dangerous dense traffic scenario, during a misty morning, 45% of the vehicles are being driven aggressively in congested traffic. These vehicles disregard traffic rules, causing frequent near-miss incidents with pedestrians and other vehicles. There are 15 pedestrians navigating the challenging weather conditions.''',
'''In a safe dense traffic scenario, during a clear evening, there are 20 vehicles and 15 pedestrians sharing the road. Some pedestrians are walking at a moderate pace, while others are using pedestrian crossings. A semi-dangerous vehicle occasionally exceeds the speed limit, posing a potential risk to other road users.''',
'''In a dangerous vehicle scenario, during a foggy and drizzly afternoon, 15% of the vehicles have malfunctioning headlights. These vehicles exhibit negligent driving behavior, disregarding traffic signs and failing to use turn signals. There are 5 pedestrians on the wet road, with 2 pedestrians running and 3 pedestrians crossing.''',
'''In a safe sparse traffic scenario, during a misty evening, there are 2 vehicles and 3 pedestrians on the road. Intern vehicles, which are still learning, occasionally make sudden stops or slow down unexpectedly. The pedestrians and other vehicles exercise caution when encountering the intern vehicles.''',
'''On a windy day with gusty winds, there is a traffic jam. There are 25 pedestrians walking, 8 pedestrians running, and 4 pedestrians crossing. Inside the traffic jam, there is a dangerous vehicle with a faulty horn, making it difficult for other road users to be alerted of its presence.''',
'''During a sunny afternoon, there are 10 pedestrians walking on the street, accompanied by 12 vehicles being driven. One vehicle has a cracked windshield, obstructing the driver's view and potentially compromising safety on the road.''',
'''In a safe dense traffic scenario, during a cloudy morning, there are 35 vehicles and 25 pedestrians sharing the road. Some pedestrians are walking briskly, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, ensuring smooth traffic flow and pedestrian safety.''',
'''In a dangerous dense traffic scenario, during a rainy evening, 55% of the vehicles are being recklessly driven in congested traffic, posing a significant risk to other road users. There are 20 pedestrians navigating the chaotic conditions, seeking shelter from the rain.''',
'''In a safe sparse traffic scenario, during a clear night, there are 4 vehicles and 3 pedestrians on the road. One of the vehicles is being driven aggressively, frequently changing lanes without signaling. The pedestrians and other vehicles maintain a safe distance from each other.''',
'''In a semi-dangerous vehicle scenario, during a drizzly morning, 20% of the vehicles have malfunctioning windshield wipers. These vehicles exhibit negligent driving behavior, compromising visibility in wet conditions. There are 7 pedestrians on the road, with one pedestrian carrying a large umbrella.''',
'''In an intern vehicle scenario, during a light rain in the evening, there are 2 intern vehicles on the road. These vehicles are still learning and occasionally hesitate at intersections, causing minor delays. There are 4 pedestrians navigating the wet conditions, exercising caution around the intern vehicles.''',
'''In a safe dense traffic scenario, during a hazy morning, there are 30 vehicles and 20 pedestrians sharing the road. Some pedestrians are jogging, while others are waiting at designated crosswalks. Some vehicles have their fog lights on, improving visibility in the challenging weather conditions.''',
'''In a semi-dangerous vehicle scenario, during a foggy and rainy afternoon, 30% of the vehicles have malfunctioning turn signals. These vehicles exhibit erratic behavior, making sudden lane changes without signaling. There are 10 pedestrians on the wet road, with 3 pedestrians running and 7 pedestrians crossing.''',
'''In a safe dense traffic scenario, during a clear morning, there are 35 vehicles and 25 pedestrians sharing the road. Some pedestrians are walking leisurely, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, prioritizing pedestrian safety and maintaining a steady pace.''',
'''In a dangerous dense traffic scenario, during a stormy evening, 75% of the vehicles are being driven aggressively in heavy traffic. These vehicles disregard lane markings and speed limits, posing a severe threat to pedestrians and other vehicles. There are 25 pedestrians navigating the challenging weather conditions.''',
'''In a safe sparse traffic scenario, during a foggy and drizzly morning, there are 2 vehicles and 4 pedestrians on the road. One of the vehicles is being driven recklessly, frequently overtaking other vehicles in low visibility conditions. The pedestrians and vehicles maintain a safe distance from each other.''',
'''In a safe dense traffic scenario, during a clear morning, there are 25 vehicles and 20 pedestrians sharing the road. Some pedestrians are walking briskly, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, ensuring smooth traffic flow and pedestrian safety.''',
'''In a semi-dangerous vehicle scenario, during a misty afternoon, 10% of the vehicles have malfunctioning headlights. These vehicles exhibit negligent driving behavior, failing to illuminate the road properly. There are 8 pedestrians on the misty road, with 2 pedestrians running and 6 pedestrians crossing.''',
'''In a safe dense traffic scenario, during a clear morning, there are 30 vehicles and 25 pedestrians sharing the road. Some pedestrians are walking leisurely, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, prioritizing pedestrian safety and maintaining a constant speed.''',
'''In a safe sparse traffic scenario, during a foggy and drizzly evening, there are 3 vehicles and 2 pedestrians on the road. One of the vehicles is being driven recklessly, frequently swerving between lanes without signaling. The pedestrians and vehicles maintain a safe distance from each other.''',
'''In a dangerous dense traffic scenario, during a misty morning, 45% of the vehicles are being driven aggressively in congested traffic. These vehicles disregard traffic rules, causing frequent near-miss incidents with pedestrians and other vehicles. There are 15 pedestrians navigating the challenging weather conditions.''',
'''In a safe dense traffic scenario, during a clear evening, there are 20 vehicles and 15 pedestrians sharing the road. Some pedestrians are walking at a moderate pace, while others are using pedestrian crossings. A semi-dangerous vehicle occasionally exceeds the speed limit, posing a potential risk to other road users.''',
'''In a dangerous vehicle scenario, during a foggy and drizzly afternoon, 15% of the vehicles have malfunctioning headlights. These vehicles exhibit negligent driving behavior, disregarding traffic signs and failing to use turn signals. There are 5 pedestrians on the wet road, with 2 pedestrians running and 3 pedestrians crossing.''',
'''In a safe sparse traffic scenario, during a misty evening, there are 2 vehicles and 3 pedestrians on the road. Intern vehicles, which are still learning, occasionally make sudden stops or slow down unexpectedly. The pedestrians and other vehicles exercise caution when encountering the intern vehicles.''',
'''On a windy day with gusty winds, there is a traffic jam. There are 25 pedestrians walking, 8 pedestrians running, and 4 pedestrians crossing. Inside the traffic jam, there is a dangerous vehicle with a faulty horn, making it difficult for other road users to be alerted of its presence.''',
'''During a sunny afternoon, there are 10 pedestrians walking on the street, accompanied by 12 vehicles being driven. One vehicle has a cracked windshield, obstructing the driver's view and potentially compromising safety on the road.''',
'''In a safe dense traffic scenario, during a cloudy morning, there are 35 vehicles and 25 pedestrians sharing the road. Some pedestrians are walking briskly, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, ensuring smooth traffic flow and pedestrian safety.''',
'''In a dangerous dense traffic scenario, during a rainy evening, 55% of the vehicles are being recklessly driven in congested traffic, posing a significant risk to other road users. There are 20 pedestrians navigating the chaotic conditions, seeking shelter from the rain.''',
'''In a safe sparse traffic scenario, during a clear night, there are 4 vehicles and 3 pedestrians on the road. One of the vehicles is being driven aggressively, frequently changing lanes without signaling. The pedestrians and other vehicles maintain a safe distance from each other.''',
'''In a semi-dangerous vehicle scenario, during a drizzly morning, 20% of the vehicles have malfunctioning windshield wipers. These vehicles exhibit negligent driving behavior, compromising visibility in wet conditions. There are 7 pedestrians on the road, with one pedestrian carrying a large umbrella.''',
'''In an intern vehicle scenario, during a light rain in the evening, there are 2 intern vehicles on the road. These vehicles are still learning and occasionally hesitate at intersections, causing minor delays. There are 4 pedestrians navigating the wet conditions, exercising caution around the intern vehicles.''',
'''In a safe dense traffic scenario, during a hazy morning, there are 30 vehicles and 20 pedestrians sharing the road. Some pedestrians are jogging, while others are waiting at designated crosswalks. Some vehicles have their fog lights on, improving visibility in the challenging weather conditions.''',
'''In a semi-dangerous vehicle scenario, during a foggy and rainy afternoon, 30% of the vehicles have malfunctioning turn signals. These vehicles exhibit erratic behavior, making sudden lane changes without signaling. There are 10 pedestrians on the wet road, with 3 pedestrians running and 7 pedestrians crossing.''',
'''In a safe dense traffic scenario, during a clear morning, there are 35 vehicles and 25 pedestrians sharing the road. Some pedestrians are walking leisurely, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, prioritizing pedestrian safety and maintaining a steady pace.''',
'''In a dangerous dense traffic scenario, during a stormy evening, 75% of the vehicles are being driven aggressively in heavy traffic. These vehicles disregard lane markings and speed limits, posing a severe threat to pedestrians and other vehicles. There are 25 pedestrians navigating the challenging weather conditions.''',
'''In a safe sparse traffic scenario, during a foggy and drizzly morning, there are 2 vehicles and 4 pedestrians on the road. One of the vehicles is being driven recklessly, frequently overtaking other vehicles in low visibility conditions. The pedestrians and vehicles maintain a safe distance from each other.''',
'''In a safe dense traffic scenario, during a clear morning, there are 25 vehicles and 20 pedestrians sharing the road. Some pedestrians are walking briskly, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, ensuring smooth traffic flow and pedestrian safety.''',
'''In a semi-dangerous vehicle scenario, during a misty afternoon, 10% of the vehicles have malfunctioning headlights. These vehicles exhibit negligent driving behavior, failing to illuminate the road properly. There are 8 pedestrians on the misty road, with 2 pedestrians running and 6 pedestrians crossing.''',
'''In a safe dense traffic scenario, during a clear morning, there are 30 vehicles and 25 pedestrians sharing the road. Some pedestrians are walking leisurely, while others are waiting for traffic lights to change. Safe vehicles operate in autonomous mode, prioritizing pedestrian safety and maintaining a constant speed.''',
'''In a safe sparse traffic scenario, during a foggy and drizzly evening, there are 3 vehicles and 2 pedestrians on the road. One of the vehicles is being driven recklessly, frequently swerving between lanes without signaling. The pedestrians and vehicles maintain a safe distance from each other.''',
'''In a dangerous dense traffic scenario, during a misty morning, 45% of the vehicles are being driven aggressively in congested traffic. These vehicles disregard traffic rules, causing frequent near-miss incidents with pedestrians and other vehicles. There are 15 pedestrians navigating the challenging weather conditions.''',
'''In a safe dense traffic scenario, during a clear evening, there are 20 vehicles and 15 pedestrians sharing the road. Some pedestrians are walking at a moderate pace, while others are using pedestrian crossings. A semi-dangerous vehicle occasionally exceeds the speed limit, posing a potential risk to other road users.''',
'''In a dangerous vehicle scenario, during a foggy and drizzly afternoon, 15% of the vehicles have malfunctioning headlights. These vehicles exhibit negligent driving behavior, disregarding traffic signs and failing to use turn signals. There are 5 pedestrians on the wet road, with 2 pedestrians running and 3 pedestrians crossing.''',
'''In a safe sparse traffic scenario, during a misty evening, there are 2 vehicles and 3 pedestrians on the road. Intern vehicles, which are still learning, occasionally make sudden stops or slow down unexpectedly. The pedestrians and other vehicles exercise caution when encountering the intern vehicles.''',
]


################################################################################################################################################################
context_head = '''
I'm using a simulator to simulate some dangerous driving scenarios. Here are some rules to generate a scenario:
1. If you want to set vehicles count, just try setting "vehicles_count".
2. If you want to set pedestrians count, just try setting "walkers_count".
3. If you want to set the percentage of the pedestrians running, just try setting "percentage_pedestrians_running".
4. If you want to set the percentage of the pedestrians jumping, you not only have to set "percentage_pedestrians_jumping", but also need to set "pedestrians_jumping_interval", indicating the interval of each jump.
5. If you want to set weather, never try to make up by yourself! You can only choose from: ClearNoon, CloudyNoon, WetNoon, WetCloudyNoon, SoftRainNoon, MidRainyNoon, HardRainNoon, ClearSunset, CloudySunset, WetSunset, WetCloudySunset, SoftRainSunset, MidRainSunset, HardRainSunset.  If there is no exact word found in the new scenario description, just try to select one of the most related words from the choice list given for setting weather. For example, scenario description may be "It is a day raining cats and dogs", then you can choose 'HardRainSunset' from the choice list; the scenario description may be "It is a cloudy evening", then you can choose 'CloudyNoon' from the choice list, etc.
6. It can be many dangerous vehicles with different attributes, and even there can be no dangerous vehicles at all. It's all up to the scenario description.
7. Some vehicles' door might be opened, you can only choose from "Front_Left, Front_Right, Rear_Left, Rear_Right, All" for indicating the door state of the vehicle. Never try to make up by yourself, just choose from the given choices.
8. You can use "for-loop" to enumerate vehicles and walkers if needed.
9. Remember to generate "import utils" before generating your code!
10. Never try to make some list index out of range!
Based on the rules given above, here are some basic utilities to generate a common scenario which contains a dangerous vehicle, do not use any APIs not mentioned in the following example code:
```python
import utils # [keep this line unchanged!]
def generate_scenario(): # [keep this line unchanged!]
    # Configs
    vehicles_count = 3 # determine the desired number of vehicles to be spawned, not final count
    walkers_count = 27 # determine the desired number of walkers to be spawned, not final count
    percentage_pedestrians_running = 0.3 # percentage ranges from 0.0 to 1.0
    percentage_pedestrians_jumping = 0.5 # percentage ranges from 0.0 to 1.0
    pedestrians_jumping_interval = 5 # this value should not be 0! Its unit is 'seconds'
    weather = utils.WeatherPresets.ClearNoon # You can choose from: from: ClearNoon, CloudyNoon, WetNoon, WetCloudyNoon, SoftRainNoon, MidRainyNoon, HardRainNoon, ClearSunset, CloudySunset, WetSunset, WetCloudySunset, SoftRainSunset, MidRainSunset, HardRainSunset.
    # Logics
    traffic_manager = utils.initialize_scenario(walkers_count, vehicles_count, percentage_pedestrians_running) # [keep this line unchanged!]
    dangerous_vehicle = utils.g_vehicles[0] # Choose one of the vehicle as a dangerous vehicle
    utils.set_vehicle_light(dangerous_vehicle, utils.VehicleLights.Open_Left_Blinker) # Choose from: Turn_off_All, Open_Position, Open_Low_Beam, Open_High_Beam, Open_Brake, Open_Right_Blinker, Open_Left_Blinker, Open_Reverse, Open_Fog, Open_Interior, Open_All
    traffic_manager.distance_to_leading_vehicle(dangerous_vehicle, 0) # Sets the minimum distance in meters that a vehicle has to keep with the others. The distance is in meters and will affect the minimum moving distance. It is computed from front to back of the vehicle objects. 
    traffic_manager.vehicle_percentage_speed_difference(dangerous_vehicle, -50) # The difference the vehicle's intended speed and its current speed limit. Speed limits can be exceeded by setting the second param to a negative value. Default is 30. Exceeding a speed limit can be done using negative percentages. 
    traffic_manager.ignore_lights_percentage(dangerous_vehicle, 100) # Between 0 and 100. Amount of times traffic lights will be ignored. 
    traffic_manager.ignore_vehicles_percentage(dangerous_vehicle, 100) # Between 0 and 100. Amount of times collisions will be ignored. 
    traffic_manager.ignore_signs_percentage(dangerous_vehicle, 100) # Between 0 and 100. Amount of times stop signs will be ignored. 
    traffic_manager.ignore_walkers_percentage(dangerous_vehicle, 100) # Between 0 and 100. Amount of times collisions will be ignored. 
    dangerous_vehicle.open_door(utils.VehicleDoors.All) # Choose from: Front_Left, Front_Right, Rear_Left, Rear_Right, All        
    utils.set_walkers_jump_interval(utils.g_world, utils.g_walkers, pedestrians_jumping_interval, percentage_pedestrians_jumping) # Set walkers jump repeatedly. Delete this line if no needed. This line of code is only for demonstration, you can delete it if the prompt does not contain related description.
    utils.g_world.set_weather(weather) # You can delete this line if there is no weather-related description in the prompt.
    utils.start_game_loop(utils.g_world) # [keep this line unchanged!]
```
Based on the example codes above, generate a new scenario described below:
'''
context_tail = '''
Start generating your code inside the function named "generate_scenario"! (Note that you can remove some codes, delete some unused parameters and functions, try to make your code as clean as possible! You do not have to generate comments!)
'''
################################################################################################################################################################

# For extracting information from an image
context_img = 'This is a traffic scenario, please generate a report on this scenario. The template is: `Time:xxx; Weather:xxx; VehicleStates:xxx; Vehicle:xxx; PedestrianCount: xxx; PercentagePedestrianRunning: xxx; VehicleDoors: [Opened OR Closed]; Location:xxx; Event:xxx; Severity:xxx.` Note that if there is a traffic accident in the given image, the severity will be higher.'
